### GET ALL ITEMS
GET http://localhost:5000/items HTTP/1.1

### GET ONE ITEM
GET http://localhost:5000/items/asda HTTP/1.1

### ADD ONE ITEM
POST http://localhost:5000/items
Content-Type: application/json

{"name": "Lisa", "age": 40, "city": "Madrid"}

### DELETE ONE ITEM
DELETE http://localhost:5000/items/0408c1d5-75eb-49f6-90a9-9d05928b8736 HTTP/1.1

### UPDATE ITEM
PUT http://localhost:5000/items/0408c1d5-75eb-49f6-90a9-9d05928b8736
Content-Type: application/json

{"name": "Updated Item"}