### TRANSACTION TEST
POST http://localhost:3040/transactions HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTI1NWEzMmE0OWY2NjBlZTQ5YWYyMyIsImlhdCI6MTYzNzAwNjk5NywiZXhwIjoxNjM3MjY2MTk3fQ.INcsUPHkqv-t3caO6z9nOVVvJdeLA2FisSpqaJ0WLNg

{
"operationDate": "2021-10-01",
"isIncome": false, 
"value": 200, 
"description": "pizza",
 "categorySpending": "Food"
// "categoryIncoming": "salary"
}

### GET ALL TRANSACTIONS
GET http://localhost:3040/transactions HTTP/1.1

### GET TRANSACTION BY ID
GET http://localhost:3040/transactions/6192c1ac66efc4eae828ee84 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTI1NWEzMmE0OWY2NjBlZTQ5YWYyMyIsImlhdCI6MTYzNzAwNjk5NywiZXhwIjoxNjM3MjY2MTk3fQ.INcsUPHkqv-t3caO6z9nOVVvJdeLA2FisSpqaJ0WLNg


### DELETE TRANSACTION BY ID
DELETE http://localhost:3040/transactions/6192c1ac66efc4eae828ee84 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTI1NWEzMmE0OWY2NjBlZTQ5YWYyMyIsImlhdCI6MTYzNzAwNjk5NywiZXhwIjoxNjM3MjY2MTk3fQ.INcsUPHkqv-t3caO6z9nOVVvJdeLA2FisSpqaJ0WLNg

### UPDATE TRANSACTION BY ID
PATCH http://localhost:3040/transactions/6179a2673339e3dbb77209b5 HTTP/1.1
Content-Type: application/json

{
"description": "Pool", 
"categorySpending": "Health"
}