### USER

### CREATE NEW USER
POST http://localhost:3040/users HTTP/1.1
Content-Type: application/json

{
    "name": "Mary", 
    "email": "mary@gmail.com", 
    // "phone": "067 111-88-00", 
    "password": "123asd"
    }

### SIGNIN
POST http://localhost:3040/users/signin HTTP/1.1
Content-Type: application/json

{
    "email": "m@ukr.net",
    "password": "123asd"
}

# {
#     "email": "nat@gmail.com", 
#     "password": "123asd"
# }

### CURRENT USER
GET http://localhost:3040/users/current HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTI1NWEzMmE0OWY2NjBlZTQ5YWYyMyIsImlhdCI6MTYzNzAwNjk5NywiZXhwIjoxNjM3MjY2MTk3fQ.INcsUPHkqv-t3caO6z9nOVVvJdeLA2FisSpqaJ0WLNg

### SIGNOUT
GET http://localhost:3040/users/signout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTI1NWEzMmE0OWY2NjBlZTQ5YWYyMyIsImlhdCI6MTYzNjk4MDE2NywiZXhwIjoxNjM3MjM5MzY3fQ.iQwHjMm72WHMiSkO3_JKLm4mKGELYk1Hl3Q8_GPSb7k

### UPDATE USER
PUT http://localhost:3040/users/619255a32a49f660ee49af23 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTI1NWEzMmE0OWY2NjBlZTQ5YWYyMyIsImlhdCI6MTYzNzAwNjk5NywiZXhwIjoxNjM3MjY2MTk3fQ.INcsUPHkqv-t3caO6z9nOVVvJdeLA2FisSpqaJ0WLNg

{"name": "Maria", "email": "mary@ukr.net"}